config/routes.rb
Trade::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount Blogit::Engine => "/blog"

  get '/auth/:provider/callback' => 'authentications#create'
  #devise_for :users, :controllers => {
  #                                    :registrations => 'registrations',
  #                                    :omniauth_callbacks => 'omniauth_callbacks'
  #                                   }
  devise_for :users, :controllers => {
                                      :registrations => 'users',
                                      :omniauth_callbacks => 'omniauth_callbacks'
                                     }

  resources :authentications

  get '/browse/:id', to: 'directory#location',  :as => 'location'
  get '/browse' => 'directory#location', :defaults => { :id => 0 }, :as => "directory"
  get '/about' => 'static#about'
  get '/tos' => 'static#tos'
  get '/transactions' => 'static#transactions'
  get '/privacy_policy' => 'static#privacy_policy'
  get '/thanks' => 'static#thanks'
  get '/under_construction' => 'static#under_construction'

  devise_scope :user do
    resources :users
    unauthenticated do
      root :to => "users#index"
    end
    authenticated :user do
      root :to => 'users#edit', as: :authenticated_root
    end
    authenticated :admin_user do
      root :to => 'admin/dashboard#index', as: :authenticated_admin_root
    end
  end

end

Blogit::Engine.routes.draw do
  devise_for :users, :controllers => {
                                      :registrations => 'registrations',
                                      :omniauth_callbacks => 'omniauth_callbacks'
                                     }
end

app/models/user.rb
require 'net/http'
require 'open-uri'
require 'json'

class User < ActiveRecord::Base
  blogs

  after_create :update_locations

  self.per_page = 20

  # GEOCODING SETTINGS:
  # address components, that used to structure users directory
  @@directory_components = [:neighborhood, :sublocality, :locality, :postal_town, :administrative_area_level_2,
    :administrative_area_level_1, :country]
  # geographic object types to try when geocoding
  @@known_object_types = [:street_address, :locality, :route]

  attr_accessor :current_password

  has_many :users_locations
  has_many :locations, through: :users_locations


  has_many :authentications
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable #, :validatable
  validates :email, uniqueness: true, presence: true, 
                    format: { with: /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/ }, if: :email_required?

  validates :password, :presence => true, :if => :password_required?
  validates_confirmation_of :password, :if => :password_required?
  validates_length_of :password, :within => 6..40, :if => :password_required?

  #validate :current_password_should_match, if: :need_password_confirmation? # checked by devise

  def self.from_omniauth(auth_data)
    auth = Authentication.where(auth_data.slice(:provider, :uid)).first_or_create! do |authentication|
      authentication.provider = auth_data.provider
      authentication.uid = auth_data.uid
      user = User.new(name: auth_data.info.name)
      user.save(validate: false)
      authentication.user = user
    end
    auth.user
  end

  def email_required?
     (authentications.empty? || !password.blank?)
  end

  def password_required?
    (authentications.empty? || !password.blank?) && (!persisted? || !self.password.nil? || !password_confirmation.nil?)
  end

  def current_password_required?
    authentications.empty? || !password.blank?
  end

  def update_with_password(params, *options)
    if !current_password_required?
        update_attributes(params, *options)
    else
      super
    end
  end

  def gravatar
    Digest::MD5.hexdigest(!email.nil? ? email.downcase.strip : '')
  end

  def geocode_locations
    unless address.strip.length > 5
      raise "address is not set"
    end
    geocoder_results = query_geocoder # reverse geocoding query happens here
    geo_object = find_known_geo_object(geocoder_results)
    used_components = []
    @@directory_components.each do |component|
      # looking for a known address components in geocoder results
      result = find_component_by_type(component, geo_object['address_components'])
      if result
        used_components << result
      end
    end
    unless used_components.length > 2
      raise "address is not specific enough"
    end
    # replaces each component with corresponding db object, creating new if necessary
    # please notice that we are creating database users_locations records here
    self.locations = convert_components_to_locations(used_components)
  end

  def update_locations
    UsersLocation.where(:user_id => id).destroy_all
    begin
      geocode_locations
    rescue
    end
  end

  protected

  def find_known_geo_object(geocoder_results)
    @@known_object_types.each do |type|
      object = find_component_by_type(type, geocoder_results)
      if object
        return object
      end
    end
    raise "no known geo object found"
  end

  def convert_components_to_locations(components)
    results = []
    while component = components.pop do
      parent_id = results.empty? ? 0 : results.last.id
      if results.last and component['long_name'] == results.last.name
        next # ignoring sublocations with identical names
      end
      location = Location.where(:parent_location_id => parent_id,
                                :name => component['long_name'],
                                :short_name => component['short_name'],
                                :location_type => component['types'].first).first_or_create
      results << location
    end
    results
  end

  def query_geocoder
    response = Net::HTTP.get('maps.googleapis.com', "/maps/api/geocode/json?address=#{URI::encode(address)}&sensor=false")
    #response = Net::HTTP.get('maps.googleapis.com', "/maps/api/geocode/json?latlng=#{latitude},#{longitude}&sensor=false")
    data = JSON.parse response
    unless data['status'] = 'OK'
      puts response
      raise "geocoding request failed"
    end
    data['results']
  end

  def find_component_by_type(type, components)
    components.each do |component|
      next unless component['types'].include?(type.to_s)
      return component
    end
    false
  end


  private

  def need_password_confirmation?
    password_required? && !new_record?
  end

  def current_password_should_match
     errors.add(:current_password, "doesn't match") if !valid_password?(self.current_password)
  end

end

app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController

  # GET /users
  def index
    #db = GeoIP::City.new(RAILS_ROOT + '/GeoLiteCity.dat', :filesystem)

    @la = params[:la]
    @lo = params[:lo]
    if @la != nil and @lo != nil and @la =~ /[-+]?(?:\d*\.\d+|\d+)/ and @lo =~ /[-+]?(?:\d*\.\d+|\d+)/
      @users = User.find_by_sql([<<SQL, {:la => @la, :lo => @lo}])
SELECT
  id, name, address, phone, aim, yim,  jabber, skype, latitude, longitude,
  ((2 * 3960 * ATAN2(SQRT(POWER(SIN((RADIANS(:la - latitude))/2), 2) + COS(RADIANS(latitude)) * COS(RADIANS(:la)) *
  POWER(SIN((RADIANS(:lo - longitude))/2), 2)),SQRT(1-(POWER(SIN((RADIANS(:la - latitude))/2), 2) + COS(RADIANS(latitude)) * COS(RADIANS(:la)) * POWER(SIN((RADIANS(:lo - longitude))/2), 2)))))) AS distance
FROM users
WHERE latitude IS NOT NULL AND longitude IS NOT NULL
ORDER BY distance
LIMIT 40
SQL
    end

    # map will be initialized with current user's location
    if current_user && current_user.latitude
      @user_json = current_user.to_json(only: [:latitude, :longitude])
    end

    respond_to do |format|
      format.html # index.html.erb
      format.js  { render :json => @users }
    end
  end

  # GET /users/:id
  def show
    @user = User.find(params[:id])
    @location = @user.locations.last
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    user_path(resource)
  end

  # The url to be used after updating a resource.
  def after_update_path_for(resource)
    user_path(resource)
  end

  def update
    super
    current_user.update_locations
  end

end

app/views/users/index.html.haml
/ ABQIAAAARBQfmn9RdvBiquR4PDW70RTBEj2q42X4eGCXtNwsuxttAIUH7hRRw1JqYFzkaCOLoyhNAylbiI4Nog
- content_for :head do
  :javascript
    $(function() {
      #{"Tradebitcoin.user = " + @user_json + ";" if @user_json}
      Tradebitcoin.view = new Tradebitcoin.views.Search();
    });

#map_canvas
#status
#controls
  %form#searchIt{:onsubmit => "return false;"}
    %input#search{:name => "search", :onfocus => "if (this.value == '  Address...') { this.style.color = '#000'; this.value=''; }", :style => "color: #999;", :type => "text", :value => "  Address..."}/
    %img#go.submit{:alt => "Go", :src => "/assets/go.png", :title => "Search for traders near this address or intersection."}/

%section.landing-text
  %h1.frontpage What are Bitcoins?
  %p To put it simply, Bitcoins are safe and secure. They are a cryptographic digital currency. They are generated at a controlled rate using a computer program. This means they will not become unstable. Bitcoins are open-source, which means nobody owns them and that Bitcoins are decentralized. There are no banks or institutions of any sort involved in the exchange of Bitcoins. This makes the cost much lower for the buyer and seller. There is no fine print or limits to transactions when you use Bitcoins because they are not regulated through a bank.
  %h1.frontpage How can I buy Bitcoins?
  %p You can purchase Bitcoins in one of two ways. Through an exchange platform, or directly through other people who have Bitcoins for sale. Both methods require the use of a traditional currency, like the US dollar. There are a number of websites that are dedicated to finding Bitcoin users such as this one. On this site you look for people who have bitcoins for sale and work out a time and place to make the trade happen!
  %h1.frontpage Are Bitcoins something new? Why haven’t I heard of them before?
  %p Bitcoins are not completely new. They have been featured in the news. Most notably, there is the story of a group anonymously acquiring Mitt Romney’s tax records and demanding one million Bitcoins as payment to release this information.

%section
  .centered-text
    %a{href: "http://bitcoinity.org/markets", target: "_blank"}
      %img{src:"http://bitcoinity.org/markets/image?span=24h&size=small", alt:"bitcoin price chart"}
    %a{href: "http://bitcoinity.org/markets", target: "_blank"}
      %img{src:"http://bitcoinity.org/markets/image?span=7d&size=small", alt:"bitcoin price chart"}
    %a{href: "http://bitcoinity.org/markets", target: "_blank"}
      %img{src:"http://bitcoinity.org/markets/image?span=30d&size=small", alt:"bitcoin price chart"}
    %a{href: "http://bitcoinity.org/markets", target: "_blank"}
      %img{src:"http://bitcoinity.org/markets/image?span=6m&size=small", alt:"bitcoin price chart"}

app/views/users/show.html.haml
- content_for :head do
  :javascript
    $(function() {
      var user = new Tradebitcoin.models.User({
        name: "#{@user.name}",
        latitude: "#{@user.latitude}",
        longitude: "#{@user.longitude}",
        address: "#{@user.address}"
      });
      Tradebitcoin.view = new Tradebitcoin.views.Profile({user: user});
    });
- if @location
  = breadcrumb_for_location(@location)
.row.profile
  .col-md-5
    %h2= @user.name
    - if current_user and current_user.id == @user.id
      .edit-button= link_to "edit profile", edit_user_registration_path, :class => "btn-success btn-sm"
    %br.clear
    %img.gravatar{src: "http://www.gravatar.com/avatar/" + @user.gravatar,  alt: "Gravatar"}
    %br.clear
    %br.clear

    - unless @user.address.nil? || @user.address.empty?
      .profile-label
        Address:
      .value
        = @user.address
    - unless @user.phone.nil? || @user.phone.empty?
      .profile-label
        Phone:
      .value
        %a{href: "callto:" + @user.phone}
          = @user.phone

    - unless (@user.aim.to_s + @user.skype.to_s + @user.yim.to_s + @user.jabber.to_s).empty?
      .profile-label Contact online:
    - unless @user.aim.nil? || @user.aim.empty?
      %a{href:"aim:goim?screenname=" + @user.aim + "&message=Bitcoin+trade."}
        %img.icon{src:"/assets/aol_64.png", alt:"AOL Instant Messenger", title:"AIM User: " + @user.aim}
    - unless @user.skype.nil? || @user.skype.empty?
      %a{href:"skype:" + @user.skype}
        %img.icon{src:"/assets/skype_icon_64x64.png", alt:"Skype", title:"Skype User: " + @user.skype}
    - unless @user.yim.nil? || @user.yim.empty?
      %a{href:"ymsgr:sendIM?" + @user.yim}
        %img.icon{src:"/assets/yahoo_64.png", alt:"Yahoo Address", title:"YIM: " + @user.yim}
    - unless @user.jabber.nil? || @user.jabber.empty?
      %a{href:"xmpp:" + @user.jabber + "?message"}
        %img.icon{src:"/assets/jabber_icon_64x64.png", alt:"Jabber", title:"Jabber: " + @user.jabber}
    %br.clear

  .col-md-7
    #map_canvas

%br.clear

#disqus_thread
:javascript
  /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
  var disqus_shortname = 'tradebitcoin'; // required: replace example with your forum shortname
  var disqus_identifier = 'user#{@user.id}';
  var disqus_title = '#{@title}';
  var disqus_url = '#{user_url(@user)}';

  /* * * DON'T EDIT BELOW THIS LINE * * */
  (function() {
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
%noscript
  Please enable JavaScript to view the
  %a{:href => "http://disqus.com/?ref_noscript"} comments powered by Disqus.
%a.dsq-brlink{:href => "http://disqus.com"}
  comments powered by
  %span.logo-disqus Disqus