config/routes.rb
Trade::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount Blogit::Engine => "/blog"

  get '/auth/:provider/callback' => 'authentications#create'
  #devise_for :users, :controllers => {
  #                                    :registrations => 'registrations',
  #                                    :omniauth_callbacks => 'omniauth_callbacks'
  #                                   }
  devise_for :users, :controllers => {
                                      :registrations => 'users',
                                      :omniauth_callbacks => 'omniauth_callbacks'
                                     }

  resources :authentications

  get '/browse/:id', to: 'directory#location',  :as => 'location'
  get '/browse' => 'directory#location', :defaults => { :id => 0 }, :as => "directory"
  get '/about' => 'static#about'
  get '/tos' => 'static#tos'
  get '/transactions' => 'static#transactions'
  get '/privacy_policy' => 'static#privacy_policy'
  get '/thanks' => 'static#thanks'
  get '/under_construction' => 'static#under_construction'

  devise_scope :user do
    resources :users
    unauthenticated do
      root :to => "users#index"
    end
    authenticated :user do
      root :to => 'users#edit', as: :authenticated_root
    end
    authenticated :admin_user do
      root :to => 'admin/dashboard#index', as: :authenticated_admin_root
    end
  end

end

Blogit::Engine.routes.draw do
  devise_for :users, :controllers => {
                                      :registrations => 'registrations',
                                      :omniauth_callbacks => 'omniauth_callbacks'
                                     }
end

app/controllers/directory_controller.rb
class DirectoryController < ApplicationController
  # users directory

  def location
    id = params[:id]
    @locations = Location.where(:parent_location_id => id)
    unless id  == 0
      @users = Location.find(id).users.where("LENGTH(name) > 1").paginate(:page => params[:page])
    end

    begin
      @location = Location.find(id)
      @title = "#{@location.name} Bitcoin Traders - Tradebitcoin.com"
    rescue
      @location = Location.new(:name => "")
    end
  end

end

app/views/directory/_breadcrumb.html.haml
- if @breadcrumb
  .directory-breadcrumb
    = link_to("World", directory_path)
    &raquo;
    - @breadcrumb.length.times do |i|
      - if i < @breadcrumb.length - 1
        = link_to(@breadcrumb[i].name, location_path(@breadcrumb[i]))
        &raquo;
      - else
        = @breadcrumb[i].name

app/views/directory/location.html.haml
- if @location.id
  = breadcrumb_for_location(@location)
- if @locations.length > 0
  .directory-title= (@location.name + " locations").strip.titleize
  .directory-content
    - @locations.each do |location|
      .directory-location.f32
        - if location.location_type == 'country'
          %span{class: "flag " + location.short_name.downcase}
        = link_to location.name, location_path(location)
    %br.clear
- if @users
  %h1.directory-title= (@location.name + " bitcoin traders").strip.titleize
  .directory-content
    %table.table.table-striped
      %tr
        %th Name
        %th Phone
        %th Address
        %th Skype
      - @users.each do |user|
        %tr.user
          %td= link_to user.name, user_path(user)
          %td= user.phone
          %td= user.address
          %td
            - unless user.skype.empty?
              %a{href:"skype:" + user.skype}
                = user.skype
    .text-center= will_paginate @users, renderer: BootstrapPagination::Rails, bootstrap: 3


%br.clear